import type { NextPage } from 'next'
import Head from 'next/head'
 

const Home: NextPage = () => {
  return (
    <div className= ''>
      <Head>
        <title>NFTDrop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-red-500 text text-4xl'>
        nft drop is available here 
      </h1>
    </div>
  )
}

export default Home
